#set of VM values of variables
vsphere_server   = "192.168.52.213"
vsphere_user     = "administrator@vsphere.local"
vsphere_password = "Asdf@Zxcv@12345"
datacenter_name = "bootlabs"
cluster_name = "Sailor"
datastore_name = "datastore1 (1)"
network_name= "VM Network"
vm_name = "jgvm"
snapshot_name = "test"
